services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'freshypass'
      MYSQL_DATABASE: freshy
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - 3306:3306
