openapi: 3.0.0
info:
  title: Freshy API
  description: API de Freshy pour la vente directe de produits
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths: {}
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token
